name: CI Tests

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.0
          cache: "yarn"

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Run unit tests
        run: yarn test:unit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.0
          cache: "yarn"

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run typecheck
        run: yarn typecheck

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.0
          cache: "yarn"

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: yarn test:e2e
